/*
 * Copyright (C) 2023,2025,2026 Dan Arrhenius <dan@ultramarin.se>
 *
 * This file is part of ujson.
 *
 * ujson is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
#include <ujson/jtokenizer.hpp>
#include <cstdint>

#if 1
#include <iostream>
using std::cerr;
using std::endl;
#endif


namespace ujson::parser {

    static constexpr const char ch_space    = 0x01; // \t \n \r ' '
    static constexpr const char ch_digit    = 0x02; // 0-9
    static constexpr const char ch_hexdigit = 0x04; // 0-9a-fA-F
    static constexpr const char ch_id_start = 0x08; // _a-zA-Z
    static constexpr const char ch_id       = 0x10; // _a-zA-Z0-9
    static constexpr const char ch_uany     = 0x20; // ch>=(char)0x80 && ch<=(char)0xbf
    static constexpr const char ch_esc_ch   = 0x40; // \"bfnrt/
    static char ch_type_map[256] = {
        // Generated by helper tool 'ch_type_map'
        0,0,0,0,0,0,0,0,0,0x1,0x1,0,0,0x1,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0x1,0,0x40,0,0,0,0,0,0,0,0,0,0,0,0,0x40,
        0x16,0x16,0x16,0x16,0x16,0x16,0x16,0x16,0x16,0x16,0,0,0,0,0,0,
        0,0x1c,0x1c,0x1c,0x1c,0x1c,0x1c,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,
        0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0,0x40,0,0,0x18,
        0,0x1c,0x5c,0x1c,0x1c,0x1c,0x5c,0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x58,0x18,
        0x18,0x18,0x58,0x18,0x58,0x18,0x18,0x18,0x18,0x18,0x18,0,0,0,0,0,
        0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,
        0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,
        0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,
        0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    };
    static inline bool is_space (const char ch)    {return ch_type_map[(uint8_t)ch] & ch_space;}
    static inline bool is_digit (const char ch)    {return ch_type_map[(uint8_t)ch] & ch_digit;}
    static inline bool is_hexdigit (const char ch) {return ch_type_map[(uint8_t)ch] & ch_hexdigit;}
    static inline bool is_id_start (const char ch) {return ch_type_map[(uint8_t)ch] & ch_id_start;}
    static inline bool is_id (const char ch)       {return ch_type_map[(uint8_t)ch] & ch_id;}
    static inline bool is_uany (const char ch)     {return ch_type_map[(uint8_t)ch] & ch_uany;}
    static inline bool is_escaped_ch (const char ch) {return ch_type_map[(uint8_t)ch] & ch_esc_ch;}

    // Type of characters in a string token
    static constexpr const char str_ch_ascii   = 0; // ' ' ! #-[ ]-DEL
    static constexpr const char str_ch_eos     = 1; // "
    static constexpr const char str_ch_esc     = 2; // '\'
    static constexpr const char str_ch_u1      = 3; // ch>=(char)0xc2 && ch<=(char)0xdf
    static constexpr const char str_ch_u2      = 4; // ch>=(char)0xe0 && ch<=(char)0xef
    static constexpr const char str_ch_u3      = 5; // ch>=(char)0xf0 && ch<=(char)0xf4
    static constexpr const char str_ch_invalid = 6; // Invalid character in a string
    static uint8_t str_ch_type_map[256] = {
        // Generated by helper tool 'ch_type_map'
        6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
        6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
        0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
        6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
        6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
        6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
        6,6,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
        3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
        4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,
        5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,6,
    };
    static inline uint8_t str_ch_type (const char ch) {return str_ch_type_map[(uint8_t)ch];}


    enum str_state_t : unsigned {
        ss_any,
        ss_uany,
        ss_escape,
        ss_escape_unicode,
    };

    enum num_state_t : unsigned {
        ns_first_digit,
        ns_integer,
        ns_find_frac_or_exp,
        ns_find_exp,
        ns_exp,
        ns_frac,
     };


    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    jtokenizer::jtokenizer ()
        : buf_pos (nullptr),
          buf_end (nullptr),
          row (0),
          col (0),
          strict (true)
    {
    }


    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    jtokenizer::jtokenizer (const std::string_view& buffer, bool strict_mode)
    {
        reset (buffer, strict_mode);
    }


    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    void jtokenizer::reset (const std::string_view& buffer, bool strict_mode)
    {
        strict = strict_mode;
        buf_pos = buffer.data ();
        buf_end = buf_pos + buffer.size ();
        token_pos = buf_pos;
        row = 0;
        col = 0;
        token.reset ();
    }


    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    std::pair<size_t, size_t> jtokenizer::pos () const
    {
        return std::make_pair (row, col);
    }


    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    void jtokenizer::set_token (jtoken::type_t type, size_t size, jtoken::error_t err)
    {
        token.type = type;
        token.data = std::string_view (token_pos, size);
        token.err_code = err;
    }


    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    void jtokenizer::scan_reserved_name (jtoken::type_t type, const char* const name, size_t name_size)
    {
        size_t name_index = 0;

        advance_pos ();

        while (true) {
            if (buf_pos >= buf_end) {
                if (strict)
                    set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_eob);
                else
                    scan_identifier ();
                return;
            }
            if (*buf_pos != name[++name_index]) {
                if (strict)
                    set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_invalid);
                else
                    scan_identifier ();
                return;
            }
            if (name_index >= (name_size-1)) {
                if (strict) {
                    set_token (type, name_size);
                    advance_pos ();
                }
                else if (((buf_pos+1)<buf_end)  &&  is_id(buf_pos[1])) {
                    // This is an identifier
                    advance_pos ();
                    scan_identifier ();
                }else{
                    set_token (type, name_size);
                    advance_pos ();
                }
                return;
            }
            advance_pos ();
        }
    }


    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    void jtokenizer::scan_identifier ()
    {
        while ((buf_pos < buf_end) && is_id(*buf_pos))
            advance_pos ();
        set_token (jtoken::tk_identifier, buf_pos-token_pos);
    }


    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    void jtokenizer::scan_string ()
    {
        str_state_t str_state = ss_any;
        int ch_count = 0;

        advance_pos ();
        token_pos = buf_pos;
        token.row = row;
        token.col = col;

        while (buf_pos < buf_end) {
            const char ch = *buf_pos;
            switch (str_state) {
            case ss_any:
                switch (str_ch_type(ch)) {
                case str_ch_ascii:
                    // Valid ASCII character
                    break;
                case str_ch_eos:
                    set_token (jtoken::tk_string, buf_pos-token_pos);
                    advance_pos ();
                    return; // String token is done
                case str_ch_esc:
                    str_state = ss_escape;
                    break;
                case str_ch_u1:
                    str_state = ss_uany;
                    ch_count = 1;
                    break;
                case str_ch_u2:
                    str_state = ss_uany;
                    ch_count = 2;
                    break;
                case str_ch_u3:
                    str_state = ss_uany;
                    ch_count = 3;
                    break;
                default:
                    set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_string_unterminated);
                    return;
                }
                break;

            case ss_uany:
                if (is_uany(ch)) {
                    if (--ch_count == 0)
                        str_state = ss_any;
                }else{
                    set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_string_utf8);
                    return;
                }
                break;

            case ss_escape:
                if (is_escaped_ch(ch)) {
                    str_state = ss_any;
                }else if (ch == 'u') {
                    str_state = ss_escape_unicode;
                    ch_count = 4;
                }else{
                    set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_string_escape);
                    return;
                }
                break;

            case ss_escape_unicode:
                if (is_hexdigit(ch)) {
                    if (--ch_count == 0)
                        str_state = ss_any;
                }else{
                    set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_string_escape);
                    return;
                }
                break;
            }

            advance_pos ();
        }
        set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_eob);
    }


    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    void jtokenizer::scan_number ()
    {
        num_state_t num_state = ns_first_digit;

        do {
            char ch = *buf_pos;

            switch (num_state) {
            case ns_first_digit:
                if (ch == '-') {
                    if (!advance_pos_and_check()) {
                        set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_eob);
                        return;
                    }
                    ch = *buf_pos;
                }
                if (ch == '0') {
                    // Possibly a fraction or exponent after
                    num_state = ns_find_frac_or_exp;
                }else if (is_digit(ch)) {
                    // Possibly more digits after
                    num_state = ns_integer;
                }else{
                    // Only a '-' with no digit after, not ok.
                    set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_number_lone_minus);
                    return;
                }
                break;

            case ns_find_frac_or_exp:
                if (ch == '.') {
                    // We have a fraction
                    num_state = ns_frac;
                    if (!advance_pos_and_check()) {
                        set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_eob);
                        return;
                    }
                    if ( ! is_digit(*buf_pos)) {
                        set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_number_no_frac);
                        return;
                    }
                    ch = *buf_pos;
                    break;
                }
                // Fall through
                // ...
            case ns_find_exp:
                if (ch == 'e' || ch == 'E') {
                    // We have an exponent
                    num_state = ns_exp;
                    if (!advance_pos_and_check()) {
                        set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_eob);
                        return;
                    }
                    ch = *buf_pos;
                    if (ch == '-' || ch == '+') {
                        if (!advance_pos_and_check()) {
                            set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_eob);
                            return;
                        }
                        ch = *buf_pos;
                    }
                    if ( ! is_digit(ch)) {
                        set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_number_no_exp);
                        return;
                    }
                }else{
                    // No exponent, number done
                    set_token (jtoken::tk_number, buf_pos-token_pos);
                    return;
                }
                break;

            case ns_exp:
                if ( ! is_digit(ch)) {
                    set_token (jtoken::tk_number, buf_pos-token_pos);
                    return;
                }

            case ns_integer:
                if ( ! is_digit(ch)) {
                    // Possibly a fraction or exponent after
                    num_state = ns_find_frac_or_exp;
                    continue;
                }
                break;

            case ns_frac:
                if ( ! is_digit(ch)) {
                    // Possibly an exponent after
                    num_state = ns_find_exp;
                    continue;
                }
                break;
            }

            advance_pos ();
        }while (buf_pos < buf_end);

        set_token (jtoken::tk_number, buf_pos-token_pos);
    }


    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    void jtokenizer::scan_comment ()
    {
        if (!advance_pos_and_check()) {
            set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_eob);
            return;
        }

        switch (*buf_pos) {
        case '/': // One line comment
            while (advance_pos_and_check()) {
                if (*buf_pos == '\n')
                    break;
            }
            set_token (jtoken::tk_comment, buf_pos-token_pos);
            if (buf_pos < buf_end)
                advance_pos ();
            break;

        case '*': // Multi line comment
            while (advance_pos_and_check()) {
                if (*buf_pos == '*') {
                    if (!advance_pos_and_check()) {
                        set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_eob);
                        return;
                    }
                    if (*buf_pos == '/') {
                        set_token (jtoken::tk_comment, buf_pos-token_pos+1);
                        advance_pos ();
                        return;
                    }
                }
            }
            set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_eob);
            break;

        default: // No comment - unexpected character
            set_token (jtoken::tk_invalid, buf_pos-token_pos, jtoken::err_unexpected_char);
        }
    }


    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    const jtoken* jtokenizer::next_token ()
    {
        // Already done scanning ?
        if (token.type == jtoken::tk_invalid  &&  token.err_code!=jtoken::ok)
            return nullptr;

        // Ignore whitespace
        while (buf_pos < buf_end  &&  is_space(*buf_pos))
            advance_pos ();

        // End of buffer ?
        if (buf_pos >= buf_end) {
            set_token (jtoken::tk_invalid, 0, jtoken::ok);
            return nullptr;
        }

        token_pos = buf_pos;
        token.row = row;
        token.col = col;

        switch (*buf_pos) {
        case '{': set_token(jtoken::tk_lcbrack, 1);   advance_pos(); break;
        case '}': set_token(jtoken::tk_rcbrack, 1);   advance_pos(); break;
        case '[': set_token(jtoken::tk_lbrack, 1);    advance_pos(); break;
        case ']': set_token(jtoken::tk_rbrack, 1);    advance_pos(); break;
        case ',': set_token(jtoken::tk_separator, 1); advance_pos(); break;
        case ':': set_token(jtoken::tk_colon, 1);     advance_pos(); break;
        case 'n': scan_reserved_name(jtoken::tk_null, "null", 4);    break;
        case 't': scan_reserved_name(jtoken::tk_true, "true", 4);    break;
        case 'f': scan_reserved_name(jtoken::tk_false, "false", 5);  break;
        case '"': scan_string(); break;
        case '/':
            if (!strict)
                scan_comment ();
            else
                set_token (jtoken::tk_invalid, buf_pos-token_pos+1, jtoken::err_unexpected_char);
            break;

        case '-':
        case '0'...'9':
            scan_number ();
            break;

        default:
            if (!strict && is_id_start(*buf_pos))
                scan_identifier ();
            else
                set_token (jtoken::tk_invalid, buf_pos-token_pos+1, jtoken::err_unexpected_char);
            break;
        }

        return &token;
    }


}
