/*
 * Copyright (C) 2026 Dan Arrhenius <dan@ultramarin.se>
 *
 * This file is part of ujson.
 *
 * ujson is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <cstdlib>
#include <cstdint>
#include <cerrno>
#include <cctype>
#include <unistd.h>
#include <getopt.h>

using std::cin;
using std::cout;
using std::cerr;
using std::endl;
using std::string;

static constexpr const char ch_space    = 0x01; // \t \n \r ' '
static constexpr const char ch_digit    = 0x02; // 0-9
static constexpr const char ch_hexdigit = 0x04; // 0-9a-fA-F
static constexpr const char ch_id_start = 0x08; // _a-zA-Z
static constexpr const char ch_id       = 0x10; // _a-zA-Z0-9
static constexpr const char ch_uany     = 0x20; // ch>=(char)0x80 && ch<=(char)0xbf
static constexpr const char ch_esc_ch   = 0x40; // \"bfnrt/
// static constexpr const char ch_esc_u    = 0x80; // u


static constexpr const char str_ch_ascii   = 0; // ' ' ! #-[ ]-DEL
static constexpr const char str_ch_eos     = 1; // "
static constexpr const char str_ch_esc     = 2; // '\'
static constexpr const char str_ch_u1      = 3; // ch>=(char)0xc2 && ch<=(char)0xdf
static constexpr const char str_ch_u2      = 4; // ch>=(char)0xe0 && ch<=(char)0xef
static constexpr const char str_ch_u3      = 5; // ch>=(char)0xf0 && ch<=(char)0xf4
static constexpr const char str_ch_invalid = 6; // Invalid character in a string


//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
int main (int argc, char* argv[])
{
    char ch = '\0';
    uint8_t mask = 0;

    cout << "    static char ch_type_map[256] = {" << endl;
    cout << "        // Generated by helper tool 'ch_type_map'" << endl;
    for (int i=0; i<16; ++i) {
        cout << "        ";
        for (int j=0; j<16; ++j) {
            mask = 0;

            // Whitespace: \t \n \r ' '
            if (ch=='\t' || ch=='\n' || ch=='\r' || ch==' ')
                mask |= (unsigned)ch_space;

            // Digit: 0-9
            if (ch>='0' && ch<='9')
                mask |= (unsigned)ch_digit;

            // Hexadecimal digit: 0-9A-Fa-f
            if ((ch>='0' && ch<='9') || (ch>='A' && ch<='F') || (ch>='a' && ch<='f'))
                mask |= (unsigned)ch_hexdigit;

            // Start of identifier: _A-Za-z
            if (ch=='_' || (ch>='A' && ch<='Z') || (ch>='a' && ch<='z'))
                mask |= (unsigned)ch_id_start;

            // Identifier: _0-9A-Za-z
            if (ch=='_' || (ch>='0' && ch<='9') || (ch>='A' && ch<='Z') || (ch>='a' && ch<='z'))
                mask |= (unsigned)ch_id;

            // Escape codes:
            switch (ch) {
            case '\\':
            case '"':
            case 'b':
            case 'f':
            case 'n':
            case 'r':
            case 't':
            case '/':
                mask |= (unsigned)ch_esc_ch;
                break;
            // case 'u':
            //     mask |= (unsigned)ch_esc_u;
            //     break;
            default:
                break;
            }

            // uany
            if (ch>=(char)0x80 && ch<=(char)0xbf)
                mask |= (unsigned)ch_uany;


            if (mask == 0) {
                cout << "0,";
            }else if (mask >= 0x80) {
                cout << "(char)0x" << std::hex << (unsigned)mask << ",";
            }else{
                cout << "0x" << std::hex << (unsigned)mask << ",";
            }
            ++ch;
        }
        cout << endl;
    }
    cout << "    };" << endl;


    cout << endl;
    cout << "    static uint8_t str_ch_type_map[256] = {" << endl;
    cout << "        // Generated by helper tool 'ch_type_map'" << endl;
    for (int i=0; i<16; ++i) {
        cout << "        ";
        for (int j=0; j<16; ++j) {

            mask = (unsigned)str_ch_invalid;

            // Valid character in a string (not " or \)
            if (ch==(char)0x20 ||
                ch==(char)0x21 ||
                (ch>=(char)0x23 && ch<=(char)0x5b) ||
                (ch>=(char)0x5d && ch<=(char)0x7f))
            {
                mask = (unsigned)str_ch_ascii;
            }

            // End-of-string: "
            if (ch=='"')
                mask = (unsigned)str_ch_eos;


            // Start of escape sequence: '\'
            if (ch=='\\')
                mask = (unsigned)str_ch_esc;

            // U1
            if (ch>=(char)0xc2 && ch<=(char)0xdf)
                mask = (unsigned)str_ch_u1;

            // U2
            if (ch>=(char)0xe0 && ch<=(char)0xef)
                mask = (unsigned)str_ch_u2;

            // U3
            if (ch>=(char)0xf0 && ch<=(char)0xf4)
                mask = (unsigned)str_ch_u3;


            cout << std::dec << (unsigned)mask << ",";
            ++ch;
        }
        cout << endl;
    }
    cout << "    };" << endl;


    return 0;
}
