.\" Manpage for ujson-verify
.\" Contact dan@ultramarin.se to correct errors or types.
.TH ujson-print 1 "" "" "User Commands"


.SH NAME
ujson-print \- Print a JSON document to standard output


.SH SYNOPSIS
.B ujson-print
[OPTIONS] [FILE]


.SH DESCRIPTION
ujson-print parses a JSON document and prints it to standard output. By default, the JSON document is parsed in relaxed mode and printed in strict mode. The document is also by default printed in a readable format. This tool can be used to convert JSON documents in relaxed form to strict form. And to make a JSON document more compact or more readable.


.SH OPTIONS
.TP
.B -c, --compact
Compact output, print the JSON document without whitespace.
.TP
.B -e, --escape-slash
When printing JSON strings, forward slash characters("/") are escaped to "\\/".
.TP
.B -s, --sort
Object members are printed in sorted order, not in natural order. Sorting is made on the member name.
.TP
.B -r, --relaxed
Numbers that are infinite or NaN are printed as (-)inf and nan, and not as null as in the JSON specification.
.TP
.B -h, --help
Print help and exit.


.SH SEE ALSO
ujson-verify(1) ujson-cmp(1) ujson-get(1) ujson-merge(1)


.SH AUTHOR
Dan Arrhenius (dan@ultramarin.se)
